agroblock/urls.py
from django.contrib import admin
from django.urls import path
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('unauthorized/', views.unauthorized, name='unauthorized'),
    path('profile/', views.profile, name='profile'),
    path('farmers/', views.profile, name='farmers'),
    path('farmers/register', views.farmer_register, name='farmer_register'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.signout, name='logout'),
    path('products/', views.products, name='products'),
    path('products/create', views.product_create, name='product_create'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('products/<int:product_id>/delete', views.product_delete, name='product_delete'),
    path('products/edit/<int:product_id>', views.product_edit, name='product_edit'),
    path('shopping-cart/payment/', views.payment, name='payment'),
    path('shopping-cart/add/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('buy/<int:product_id>', views.buy, name='buy'),
    path('shopping-cart/subtract/<int:product_id>', views.subtract_from_cart, name='subtract_from_cart'),
    path('shopping-cart/delete/<int:product_id>', views.delete_from_cart, name='delete_from_cart'),
    path('shopping-cart/clear', views.clear_cart, name='clear_cart'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Farmer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    farm_name = models.CharField(max_length=100, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    saldo = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.user.username

    class Meta:
        db_table = 'farmers'


class Agricultural_product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)        
    stock = models.IntegerField()
    image = models.ImageField(upload_to='static/uploads/')
    seller = models.ForeignKey(Farmer, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'agricultural_products'    


class Order(models.Model):
    user = models.ForeignKey(Farmer, on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    order_status = models.CharField(max_length=20, default='Pending')
    total = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = 'orders' 


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Agricultural_product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = 'orderdetails'

main/forms.py
from django.forms import ModelForm
from .models import Agricultural_product, Farmer
from django.contrib.auth.models import User

class ProductForm(ModelForm):
    class Meta:
        model = Agricultural_product
        exclude = ('seller',)

class FarmerForm(ModelForm):
    class Meta:
        model = Farmer
        exclude = ('user', 'saldo')

class UserProfileForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    #def __init__(self, *args, **kwargs):
    #    super(UserProfileForm, self).__init__(*args, **kwargs)
    #    self.fields['email'].widget.attrs['readonly'] = True  # Si deseas hacer el campo de correo electrónico solo de lectura

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .forms import ProductForm, FarmerForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from .decorators import is_not_farmer, is_farmer
from .models import Agricultural_product, Farmer
from django.contrib.auth.hashers import check_password
from main.util import ShoppingCart


def home(request):
    products_list = Agricultural_product.objects.all()
    return render(request, 'home.html', {'products_list': products_list})


@login_required
def profile(request):
    try:
        farmer = Farmer.objects.get(user=request.user)
        products_list = Agricultural_product.objects.filter(seller=farmer)
    except Farmer.DoesNotExist:
        farmer = None
        products_list = None

    user_info = {
        'username' : request.user.username,
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
        'email': request.user.email,
    }
    form = UserProfileForm(initial=user_info)

    if is_farmer:
        form.fields['email'].widget.attrs['readonly'] = True
        
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            password = request.POST['password']
            if check_password(password, request.user.password):
                form.save()
                return redirect('profile')
            else:
                return render(request, 'profile.html', {
                'products_list': products_list,
                'form': form,
                'error' : 'Verifica tu contraseña'
                })
        else:
            return render(request, 'profile.html', {
                'products_list': products_list,
                'form': form,
                'error' : 'Verifique los datos ingresados'
            })
    else:
        return render(request, 'profile.html', {
            'products_list': products_list,
            'form': form
        })



def unauthorized(request):
    return render(request, 'unauthorized_page.html')


@is_not_farmer
@login_required
def farmer_register(request):
    if request.method == 'GET':
        return render(request, 'farmer_register.html', {
            'form': FarmerForm
        })
    else:
        try:
            form = FarmerForm(request.POST)
            if form.is_valid():
                farmer = form.save(commit=False)
                farmer.user = request.user  # Asignar el usuario actual al campo 'user' del Farmer
                farmer.saldo = 0
                farmer.save()
                return redirect('profile')
        except ValueError:
            return render(request, 'farmer_register.html', {
                'form': FarmerForm,
                "error": "Invalid data"
            })


def products(request):

    query = request.GET.get('q')

    products_list = Agricultural_product.objects.all()
    
    if query:
        products_list = products_list.filter(name__icontains=query)

    return render(request, 'products.html', {'products_list': products_list})


@is_farmer
@login_required
def product_create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            new_product = form.save(commit=False)

            # Obtén el Farmer asociado al usuario autenticado
            farmer = Farmer.objects.get(user=request.user)

            new_product.seller = farmer
            new_product.save()

            return redirect('products')
    else:
        form = ProductForm()

    return render(request, 'product_create.html', {'form': form})

        

def product_detail(request, product_id):
    product = get_object_or_404(Agricultural_product, pk=product_id)
    return render(request, 'product_detail.html', {
        'product' : product,
    })


def product_delete(request, product_id):
    product = get_object_or_404(Agricultural_product, pk=product_id)
    if request.method == 'GET':
        if request.user == product.seller.user:
            product.delete()
            return redirect('profile')
    

@login_required
def product_edit(request, product_id):
    if request.method == 'GET':
        product = get_object_or_404(Agricultural_product, pk=product_id)
        if request.user == product.seller.user:
            form = ProductForm(instance=product)
            return render(request, 'product_edit.html', {
                'product' : product,
                'form' : form
            })
        else:
            return redirect('profile')
    
    else:
        try:
            product = get_object_or_404(Agricultural_product, pk=product_id)
            if request.user == product.seller.user:
                form = ProductForm(request.POST, instance=product)
                form.save()
                return redirect('profile')
        except ValueError:
            return render(request, 'product_edit.html', {
            'product' : product,
            'form' : form,
            'error' : 'Error Al Actualizar Producto'
            })




def signup(request):

    if request.method == 'GET':
        return render(request, 'signup.html', {
            'form': UserCreationForm
        })
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('products')
            except IntegrityError:
                return render(request, 'signup.html', {
                    'form': UserCreationForm,
                    "error": "User already exists"
                })
        return render(request, 'signup.html', {
            'form': UserCreationForm,
            "error": "Password do not match"
        })


def signout(request):
    logout(request)
    return redirect('home')


def signin(request):

    if request.method == 'GET':
        return render(request, 'signin.html')
    else:
        print(request.POST)
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        
        if user is None:
            return render(request, 'signin.html', {
                'error' : 'User or password is incorrect'
            })
        else:
            login(request, user)
            return redirect('home')



def shopping_cart(request):
    products = Agricultural_product.objects.all()
    return render(request, 'shopping_cart.html',{
        'products_list' : products
    })


def buy(request, product_id):
    cart = ShoppingCart(request)
    product = Agricultural_product.objects.get(id=product_id)
    cart.add(product)
    return redirect('payment')

def add_to_cart(request, product_id):
    cart = ShoppingCart(request)
    product = Agricultural_product.objects.get(id=product_id)
    cart.add(product)
    return redirect(request.META.get('HTTP_REFERER', 'products'))

def subtract_from_cart(request, product_id):
    cart = ShoppingCart(request)
    product = Agricultural_product.objects.get(id=product_id)
    cart.subtract(product)
    return redirect(request.META.get('HTTP_REFERER', 'products'))

def delete_from_cart(request, product_id):
    cart = ShoppingCart(request)
    product = Agricultural_product.objects.get(id=product_id)
    cart.delete(product)
    return redirect(request.META.get('HTTP_REFERER', 'products'))

def clear_cart(request):
    cart = ShoppingCart(request)
    cart.clear()
    return redirect(request.META.get('HTTP_REFERER', 'products'))

def payment(request):
    
    return render(request, 'payment.html')

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AgroBlock</title>
    {% load bootstrap4 %} 
    {% bootstrap_css %}
    {% load widget_tweaks %}
    {% load static %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

</head>
<body>

    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="/">AgroBlock</a>
        <ul class="navbar-nav   ">

            <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                <a class="nav-link" href="/">Home</a>
            </li>

            <li class="nav-item {% if request.path == '/products/' %}active{% endif %}">
                <a class="nav-link" href="/products/">Products</a>
            </li>
             

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/logout/">Logout</a>
                </li>

            {% else %}
                
                <li class="nav-item {% if request.path == '/signin/' %}active{% endif %}">
                    <a class="nav-link" href="/signin/">SignIn</a>
                </li>

                <li class="nav-item {% if request.path == '/signup/' %}active{% endif %}">
                    <a class="nav-link" href="/signup/">SignUp</a>
                </li>
            {% endif %}

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/profile/">Profile</a>
                </li>
            {% endif %}
                
        </ul>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
        
        {% if user.is_authenticated %}
            {% include 'widget_cart.html' %}
        {% endif %}
    </div>
    <div>
        <footer class="footer bg-dark text-white mt-5">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 mt-3">
                        <p>&copy; 2023 Agroblock. Todos los derechos reservados.</p>
                    </div>
                    <div class="col-md-6 text-right mt-3">
                        <p>Contacto: info@agroblock.com</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    
</body>
</html>

main/templates/farmer_register.html
{% extends 'base.html' %}

{% block content%}

<section class=" gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <form action="{% url 'farmer_register'%}" method="POST">
                            <h2 class="fw-bold mb-2 text-uppercase">REGISTER FARMER</h2>
                            {{error}}
                            {% csrf_token %}
                        
                            <p class="text-white-50 mb-3">Please complete the information!</p>

                            <div class="form-outline form-white mb-3">
                                <input type="text" name="farm_name" placeholder="Farm name" class="form-control form-control-lg" />
                            </div>

                            <div class="form-outline form-white mb-3">
                                <input type="text" name="address" placeholder="Farm address" class="form-control form-control-lg" />
                            </div>

                            <div class="form-outline form-white mb-4">
                                <input type="text" name="phone_number" placeholder="Farm phone number" class="form-control form-control-lg" />
                            </div>

                            <div class="form-outline form-white mb-4">
                                <textarea name="bio" placeholder="Biography" class="form-control" rows="4"></textarea>
                            </div>


                            <button class="btn btn-outline-light btn-lg px-5" type="submit">REGISTER</button>
                        </form>
                        

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

main/templates/product_create.html
{% extends 'base.html' %}

{% block content %}


<section class=" gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <form action="{% url 'product_create' %}" method="POST" enctype="multipart/form-data">
                            <h2 class="fw-bold mb-4 text-uppercase">CREAR PRODUCTO</h2>
                            {{error}}
                            {% csrf_token %}

                            <div class="form-outline form-white mb-4">
                                <input type="text" name="name" placeholder="Product Name" class="form-control" />
                            </div>
                        
                            <div class="form-outline form-white mb-4">
                                <textarea name="description" placeholder="Description" class="form-control" rows="5"></textarea>
                            </div>
                        
                            <div class="form-outline form-white mb-4">
                                <input type="number" name="price" placeholder="Price" class="form-control" />
                            </div>
                        
                            <div class="form-outline form-white mb-4">
                                <input type="number" name="stock" placeholder="Stock" class="form-control" />
                            </div>
                        
                            <div class="form-outline form-white mb-4">
                                <input type="file" name="image" class="form-control" accept="image/*" />
                            </div>                        

                            <div>
                                <button class="btn btn-outline-light btn-lg px-5" type="submit">CREAR PRODUCTO</button>
                            </div>
                            
                            <a href="javascript:history.go(-1)">Regresar</a>

                        </form>
                        

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

main/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h1 class="title text-center">CATÁLOGO</h1>
    <div class="container justify-content-end">
        <form class="form-inline justify-content-end" method="GET" action="/products/">
            <div class="d-flex">
                <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}">
                <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
            </div>
        </form>
    </div>
    
    <div class="container mt-3 mb-3">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                {% if user.farmer_set.all %}
                    <a href="{% url 'product_create' %}" class="btn btn-primary mb-3">Crear Nuevo Producto</a>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-lg-4 row-cols-lg-5">
            {% for agricultural_product in products_list %}
                <div class="col mb-4">
                    <div class="card mb-4 bg-dark">
                        <a style="text-decoration: none;" href="{% url 'product_detail' agricultural_product.id %}">
                            <div class="row shadow-sm">
                                <div class="col m-1">
                                    <img src="{{ agricultural_product.image.url }}" alt="{{ agricultural_product.name }}" class="card-img-top" style="height: 225px; width: 100%; display: block; border-radius: 5%;">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <h5 class="card-title" style="max-height: 1.2em; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">{{ agricultural_product.name }}</h5>
                                    <p class="card-text">Precio: {{ agricultural_product.price }}</p>
                                    <p class="card-text">Stock: {{ agricultural_product.stock }}</p>
                                </div>
                                {% if user.is_authenticated%}
                                    <div class="col text-center m-4">
                                        <button class="btn btn-primary">
                                            <a href="{% url 'add_to_cart' agricultural_product.id %}" style="color: azure; text-decoration: none;">Add to Cart</a>
                                        </button>
                                    </div>
                                {% else %}
                                    <div class="col text-center m-4">
                                        <button class="btn btn-primary">
                                            <a href="{% url 'signup'%}" style="color: azure; text-decoration: none;">Add to Cart</a>
                                        </button>
                                    </div>
                                {% endif %}
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    


{% endblock %}

main/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        
    <h1 class="title text-center">PERFIL</h1>
    {% if user.farmer_set.all %}
        <section class="gradient-custom">
            <div class="container py-5 h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-8 col-lg-8 col-xl-6">
                        <div class="card bg-dark text-white" style="border-radius: 1rem;">
                            <div class="card-body p-5 text-center">
                                <h1 class="text-center mb-5">{{user.username|upper}}</h1>
                                {{error}}
                                {% csrf_token %}
                                
                                <p class="text-white-50 mb-3">Completa tu perfil</p>
                                <form method="POST">
                                    {% csrf_token %}

                                    <div class="form-outline form-white mb-4">
                                        <input type="text" name="username" class="form-control" placeholder="Username" value="{{ form.initial.username }}"/>
                                    </div>

                                    <div class="form-outline form-white mb-4">
                                        <input type="text" name="first_name" class="form-control" placeholder="First name" value="{{ form.initial.first_name }}"/>
                                    </div>
                            
                                    <div class="form-outline form-white mb-4">
                                        <input type="text" name="last_name" class="form-control" placeholder="Last name" value="{{ form.initial.last_name }}"/>
                                    </div>

                                    <div class="form-outline form-white mb-4">
                                        <input type="text" name="email" class="form-control" placeholder="email" value="{{ form.initial.email }}"/>
                                    </div>

                                    <div class="form-outline form-white mb-4">
                                        <input type="password" name="password" class="form-control" placeholder="password"/>
                                    </div>

                                    <button class="btn btn-secondary">
                                        Actualizar
                                    </button>
                                </form>

                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-md-8 col-lg-8 col-xl-6">
                        <div class="card bg-dark text-white" style="border-radius: 1rem;">
                            <div class="card-body p-5 text-center">
                                <h1 class="text-center mb-5">Tus productos</h1>
                                <div class="container overflow-y-auto mb-3 bg-dark" style="max-height: 350px;">
                                    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 bg-dark text-light">
                                        {% for agricultural_product in products_list %}
                                            <div class="col mb-4">
                                                <div class="card mb-4 bg-dark">
                                                    <a style="text-decoration: none;" href="{% url 'product_detail' agricultural_product.id %}">
                                                        <div class="row shadow-sm">
                                                            <div class="col m-1">
                                                                <img src="{{ agricultural_product.image.url }}" alt="{{ agricultural_product.name }}" class="card-img-top" style="height: 150px; width: 100%; display: block; border-radius: 5%;">
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col">
                                                                <h5 class="card-title" style="max-height: 1.2em; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">{{ agricultural_product.name }}</h5>
                                                                <p class="card-text">Precio: {{ agricultural_product.price }}</p>
                                                                <p class="card-text">Stock: {{ agricultural_product.stock }}</p>
                                                            </div>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                

                                <div class="col-md-12 text-center">
                                    <a href="{% url 'product_create' %}" class="btn btn-primary mb-1">Crear Nuevo producto</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    {% else %}

        <section class="gradient-custom">
            <div class="container py-5 h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-8 col-lg-8 col-xl-6">
                        <div class="card bg-dark text-white" style="border-radius: 1rem;">
                            <div class="card-body p-5 text-center">
                                <h1 class="text-center mb-4">{{user.username|upper}}</h1>
                                
                                
                                <p class="text-white-50 mb-3">Completa tu perfil</p>
                                <form method="POST">
                                    <div class="text-red mb-3">{{error}}</div>
                                    {% csrf_token %}

                                    <div class="form-outline form-white mb-4">
                                        <input type="text" name="username" class="form-control" placeholder="Username" value="{{ form.initial.username }}"/>
                                    </div>

                                    <div class="form-outline form-white mb-4">
                                        <input type="text" name="first_name" class="form-control" placeholder="First name" value="{{ form.initial.first_name }}"/>
                                    </div>
                            
                                    <div class="form-outline form-white mb-4">
                                        <input type="text" name="last_name" class="form-control" placeholder="Last name" value="{{ form.initial.last_name }}"/>
                                    </div>

                                    <div class="form-outline form-white mb-4">
                                        <input type="text" name="email" class="form-control" placeholder="email" value="{{ form.initial.email }}"/>
                                    </div>

                                    <div class="form-outline form-white mb-4">
                                        <input type="password" name="password" class="form-control" placeholder="password"/>
                                    </div>

                                    <div class="mb-4">
                                        <button class="btn btn-secondary">
                                            Actualizar
                                        </button>
                                    </div>
                                    
                                </form>

                                <div class="mb-1">
                                    {% if user.email == '' or user.firts_name == '' or user.last_name == '' %}
                                        <button class="btn btn-secondary" onclick="mostrarDialogo('Completa todos tus datos antes de aplicar.')">Aplicar a Farmer</button>
                                    {% else %}
                                        <button class="btn btn-danger"><a style="color: inherit; text-decoration: none;" href="{% url 'farmer_register' %}">Aplicar a Farmer</a></button>
                                    {% endif %}
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% endif %}

    <script>
        function mostrarDialogo(mensaje) {
            var confirmacion = confirm(mensaje);
        }
    </script>
        
{% endblock %}

main/templates/shopping_cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<p>Hola</p>

{% endblock %}